# Generated by Django 4.0 on 2022-11-11 10:09

import customer.models
from django.db import migrations, models
import django.db.models.deletion
import merchant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0003_alter_item_store'),
        ('authentication', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[(customer.models.Gender['MALE'], 'Male'), (customer.models.Gender['FEMALE'], 'Female'), (customer.models.Gender['OTHER'], 'Other')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'customer_addresses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('total', models.FloatField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[(customer.models.PaymentMethod['CASH'], 'Cash'), (customer.models.PaymentMethod['CARD'], 'Card'), (customer.models.PaymentMethod['NETBANKING'], 'NetBanking'), (customer.models.PaymentMethod['UPIWALLET'], 'UPIWallet')], default=customer.models.PaymentMethod['CASH'], max_length=50)),
                ('payment_status', models.CharField(choices=[(customer.models.PaymentStatus['PENDING'], 'Pending'), (customer.models.PaymentStatus['SUCCESS'], 'Success'), (customer.models.PaymentStatus['FAILED'], 'Failed')], default=customer.models.PaymentStatus['PENDING'], max_length=50)),
                ('status', models.CharField(choices=[(customer.models.OrderStatus['PENDING'], 'Pending'), (customer.models.OrderStatus['CONFIRMED'], 'Confirmed'), (customer.models.OrderStatus['CANCELLED'], 'Cancelled'), (customer.models.OrderStatus['DELIVERED'], 'Delivered')], default=customer.models.OrderStatus['PENDING'], max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customeraddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField(blank=True, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[(merchant.models.DiscountType['PERCENTAGE'], 'percentage'), (merchant.models.DiscountType['FLAT'], 'flat')], max_length=50, null=True)),
                ('amount_after_discount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[(customer.models.OrderItemStatus['PENDING'], 'Pending'), (customer.models.OrderItemStatus['CONFIRMED'], 'Confirmed'), (customer.models.OrderItemStatus['CANCELLED'], 'Cancelled'), (customer.models.OrderItemStatus['DELIVERED'], 'Delivered')], default=customer.models.OrderItemStatus['PENDING'], max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.item')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
