# Generated by Django 4.0 on 2022-11-11 10:09

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(authentication.models.UserTypes['MERCHANT'], 'MERCHANT'), (authentication.models.UserTypes['CUSTOMER'], 'CUSTOMER')], default=authentication.models.UserTypes['CUSTOMER'], max_length=50),
        ),
    ]
